indian_veggies = [
    "Bitter Gourd (Karela)",
    "Bottle Gourd (Lauki)",
    "Ridge Gourd (Turai)",
    "Snake Gourd (Galka)",
    "Pointed Gourd (Parwal)",
    "Drumstick (Moringa)",
    "Taro Root (Arbi)",
    "Elephant Foot Yam (Suran)",
    "Ash Gourd (Petha)",
    "Ivy Gourd (Tindora)",
    "Fenugreek Leaves (Methi)",
    "Amaranth Leaves (Patra)",
    "Colocasia Leaves (Arbi ke Patte)",
    "Beet Greens (Chukandar ke Patte)",
    "Mustard Greens (Sarson)",
    "Radish Greens (Mooli ke Patte)",
    "Spinach (Palak)",
    "Fenugreek Seeds Sprouts (Methi Dana)",
    "Cluster Beans (Gawar Phali)",
    "French Beans",
    "Yardlong Beans (Bora)",
    "Broad Beans (Sem)",
    "Green Peas (Matar)",
    "Corn (Makai)",
    "Bamboo Shoots (Karil)",
    "Jackfruit (Kathal)",
    "Raw Banana (Kachcha Kela)",
    "Green Papaya (Kachcha Papita)",
    "Indian Gooseberry (Amla)",
    "Curry Leaves (Kadi Patta)",
    "Raw Mango (Keri)",
    "Sponge Gourd (Nenua)",
    "Brinjal (Baingan)",
    "Lady Finger (Bhindi)",
    "Cabbage (Patta Gobi)",
    "Cauliflower (Phool Gobi)",
    "Radish (Mooli)",
    "Turnip (Shalgam)",
    "Carrot (Gajar)",
    "Tomato (Tamatar)"
]

fruits = [
    "Mango",
    "Banana",
    "Apple",
    "Papaya",
    "Guava",
    "Pineapple",
    "Pomegranate",
    "Watermelon",
    "Muskmelon",
    "Lychee",
    "Orange",
    "Sweet Lime (Mosambi)",
    "Chikoo (Sapodilla)",
    "Grapes",
    "Custard Apple",
    "Jackfruit",
    "Tamarind",
    "Jamun (Java Plum)",
    "Star Fruit",
    "Fig",
    "Blackberry",
    "Pear",
    "Peach",
    "Plum",
    "Apricot",
    "Kiwi",
    "Avocado",
    "Coconut",
    "Amla (Indian Gooseberry)",
    "Ber (Jujube)"
]

veggies = [
    "Brinjal (Eggplant)",
    "Bitter Gourd",
    "Bottle Gourd",
    "Cabbage",
    "Carrot",
    "Cauliflower",
    "Cluster Beans",
    "Drumstick",
    "French Beans",
    "Green Chillies",
    "Green Peas",
    "Ivy Gourd",
    "Lady Finger (Okra)",
    "Pumpkin",
    "Radish",
    "Ridge Gourd",
    "Spinach",
    "Sweet Potato",
    "Tomato",
    "Turnip",
    "Yam",
    "Fenugreek Leaves (Methi)",
    "Mustard Greens",
    "Ash Gourd",
    "Coriander Leaves",
    "Beetroot",
    "Elephant Foot Yam",
    "Snake Gourd",
    "Pointed Gourd (Parwal)",
    "Amaranth Leaves"
]